INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 6, '847', '555', 65, 65, 3, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 7, 'Zm11', 'Introducción A La Mediación', 10, 10, 4, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 8, 'Dmn', 'Gadgiugih', 40, 40, 5, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 9, 'N1551', 'Comunicacion', 100, 100, 6, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 10, 'Cp1Im1', 'Lengua Castellana Y Literatura', 100, 100, 7, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 11, 'Cp2Im1', 'Lengua Castellana Y Literatura', 100, 100, 8, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 12, 'Cq11M1', 'Quimica', 76, 76, 9, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 13, 'Cq21M1', 'Fisica', 76, 76, 10, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 14, 'Cq31M1', 'Algoritmica', 76, 76, 11, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 15, 'Cr11I1', 'Quimica', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 16, 'Cis112', 'Orientación Educacional Y Sociolaboral ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 17, 'Cis113', 'Dibujo Técnico ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 18, 'Cis114', 'Gabinete De Informatica - Laboratorio', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 19, 'Cis115', 'Gabinete De Informatica - Software ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 20, 'Cis117', 'Matemática Aplicada  A La Informática ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 21, 'Cis11', 'Lengua Y Literatura Castellana ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 22, 'Cis12', 'Guarani Ñe´e ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 23, 'Cis28', 'Historia Y Geografia ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 24, 'Cis13', 'Lengua  Extranjera ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 25, 'Cis14', 'Ciencias Naturales Y Salud ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 26, 'Cis15', 'Física ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 27, 'Cis16', 'Quimica', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 28, 'Cis17', 'Matematica ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 29, 'Cis18', 'Historia Y Geografia ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 30, 'Cis19', 'Formación Ética Y Ciudadana ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 31, 'Cis120', 'Sociologia Y Antropologia Culutral ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 32, 'Cis121', 'Educación Física ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 33, 'Ci122', 'Orientación Educacional Y Sociolaboral ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 34, 'Cis123', 'Dibujo Técnico ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 35, 'Cis124', 'Gabinete De Informática - Laboratorio ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 36, 'Cis125', 'Laboratorio De Informática - Sofware ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 37, 'Cis110', 'Antropología Social Y Cultural', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 38, 'Cis111', 'Educación Fisica ', 1, 1, 12, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 39, 'Cr11B1', 'Quimica', 1, 1, 13, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 40, 'Cbs18', 'Historia Y Geografia ', 1, 1, 13, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 41, 'Cbs19', 'Psicologia ', 1, 1, 13, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 42, 'Cbs110', 'Antropologia Social ', 1, 1, 13, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 43, 'Cbs111', 'Educación Fisica ', 1, 1, 13, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 44, 'Cbs112', 'Artes', 1, 1, 13, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 45, 'Cbs113', 'Logica Matematica', 1, 1, 13, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 46, 'Cbs114', 'Geología ', 1, 1, 13, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 47, 'Cbs115', 'Educación Ambienta', 1, 1, 13, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 48, 'Cbs11', 'Lengua Castellana Y Literatura', 1, 1, 13, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 49, 'Cbs12', 'Guarani Ñe´e ', 1, 1, 13, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 50, 'Cbs13', 'Lengua Extranjera ', 1, 1, 13, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 51, 'Cbs15', 'Física ', 1, 1, 13, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 52, 'Cbs16', 'Quimica ', 1, 1, 13, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 53, 'Cbs17', 'Matemática', 1, 1, 13, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 54, 'Cr21I1', 'Fisica', 1, 1, 14, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 55, 'Cis21', 'Lengua Castellana Y Literatura ', 1, 1, 14, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 56, 'Cis22', 'Guarani Ñe´e ', 1, 1, 14, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 57, 'Cis23', 'Lengua Extrajera ', 1, 1, 14, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 58, 'Cis24', 'Ciencias Naturales Y Salud ', 1, 1, 14, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 59, 'Cis25', 'Fisica ', 1, 1, 14, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 60, 'Cis26', 'Quimica', 1, 1, 14, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 61, 'Cis27', 'Matemática ', 1, 1, 14, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 62, 'Cis29', 'Educación Vial ', 1, 1, 14, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 63, 'Cis210', 'Educación Fisica', 1, 1, 14, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 64, 'Cis211', 'Gabinete De Informática - Laboratorio ', 1, 1, 14, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 65, 'Cis212', 'Gabinete De Informática - Sowftware', 1, 1, 14, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 66, 'Cis213', 'Gabinete De Laboratorio - Hardware ', 1, 1, 14, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 67, 'Cis214', 'Algoritmica ', 1, 1, 14, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 68, 'Cis215', 'Administración Financiera', 1, 1, 14, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 69, 'Cis216', 'Matemática Aplicada A La Informatica ', 1, 1, 14, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 70, 'Cbs14', 'Ciencias Naturales Y Salud ', 1, 1, 14, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 71, 'Cr31I1', 'Algoritmica', 1, 1, 15, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 72, 'Cs11I1', 'Quimica', 1, 1, 16, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 73, 'Cs11B1', 'Quimica', 1, 1, 17, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 74, 'Cs21I1', 'Fisica', 1, 1, 18, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 75, 'Cs21B1', 'Fisica', 1, 1, 19, '0',0);
INSERT INTO   subjects(  subj_id,  subj_code,  subj_name,  subj_durationhs,  subj_weeklyhs,  sems_id,  subj_mattertype, subj_carord) VALUES ( 76, 'Cs31I1', 'Algoritmica', 1, 1, 20, '0',0);