INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (101,'Administracion General','Adm',101,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (102,'Educacion  Media','Em',102,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (103,'Educacion Escolar Basica Divina Esperanza','Eebde',103,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (104,'Nivel Inicial Esperancita','Eni',103,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (105,'Formación Profesional','Pro',104,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (106,'Formación Docente Contínua','Fdc',105,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (107,'Formación Docente Inicial','Fdi',105,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (108,'Licenciaturas','Lic',105,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (109,'Profesionalización','Prof',105,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (110,'Facultad De Ciencias De La Salud','Fcdls',107,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (111,'Facultad De Ciencias Empresariales','Fce',107,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (112,'Facultad De Ciencia, Arte Y Tecnologia','Fcit',107,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (113,'Facultad De Ciencias Jurídicas, Humanas Y Sociales','Fcjs',107,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (114,'Facultad De Ciencias Sociales Y Humanidades','Fcsh',107,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (115,'Licenciatura En Ciencias Contables','Gc',107,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (116,'Maestria En Educacion Y Desarrollo Humano','Medh',107,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (117,'Ingenieria Comercial','Mk',107,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (118,'Posgrado','Pg',107,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (119,'Rectorado','Rec',107,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (120,'Licenciatura En Trabajo Social','Ts',107,'Blank.jpg');
INSERT INTO   faculties (facu_id,facu_name,facu_code,facu_unit_id,facu_logo) VALUES (121,'Facultad Creada Para Pruebas Ag','Fag',107,'Blank.jpg');